//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drivers_License.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDriversLicenseDetail
    {
        public int Id { get; set; }
        public string License_number { get; set; }
        public Nullable<System.DateTime> Issue_date { get; set; }
        public Nullable<System.DateTime> Expiry_date { get; set; }
        public Nullable<int> PersonId { get; set; }
        public int LicenseTypeId { get; set; }
    
        public virtual tblPersonDetail tblPersonDetail { get; set; }
        public virtual tblLicenseType tblLicenseType { get; set; }
    }
}
