//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drivers_License.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLicenseType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLicenseType()
        {
            this.tblDriversLicenseDetails = new HashSet<tblDriversLicenseDetail>();
        }
    
        public int Id { get; set; }
        public string LicenseTypeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDriversLicenseDetail> tblDriversLicenseDetails { get; set; }
    }
}
